### ISSUE TITLE
add addInfo back into code

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint-cloud-foundry#22]
removed in https://github.com/abaplint/abaplint-cloud-foundry/pull/18/files

@sbcgua 

#18

**Comment by sbcgua** [comment]
I have another suggestion for this. Either external log system if this is for internal usage (I'll propose more specifically later) or the same result in the fronpage but with another approach (custom logger library transport)

**Comment by larshp** [comment]
just need easy access to

* request type
* Object Type(if its check_object)
* inbound payload size
* response time

last 10 requests would be okay

**Comment by sbcgua** [comment]
OK, got it

**Comment by larshp** [comment]
and if the processing for some reason gives an exception, also add to list

**Comment by sbcgua** [comment]
OK. But it's a separate PR please. I'd like to go on with docker first and then improve the logging

**Comment by larshp** [comment]
yea, thats why I opened it as an issue :)

**Comment by sbcgua** [comment]
linked to #19

**Comment by sbcgua** [comment]
hmmm, how to self assign ? Seems like no such option in this repo, strange ?

**Comment by larshp** [comment]
@sbcgua I've invited you, try again

**Comment by sbcgua** [comment]
yeap, works now :+1:

**Comment by sbcgua** [comment]
can be closed ?
