### ISSUE TITLE
ignore favicon requests in log

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint-cloud-foundry#29]
![image](https://user-images.githubusercontent.com/5888506/80498730-61e39700-896c-11ea-8e7f-c5644f56e7a1.png)

**Comment by sbcgua** [comment]
or maybe add a favicon instead ?

**Comment by larshp** [comment]
yea, also good

**Comment by sbcgua** [comment]
btw, can this be closed ?

**Comment by larshp** [comment]
yea
