### ISSUE TITLE
Docker-Hub contains abaplint/abaplint-backend but no image

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-cloud-foundry#33]
Docker-Hub contains abaplint/abaplint-backend but no image can be pulled.

Is there a problem with the publishing process or is no image planned.
If the latter, the entry should be removed from Docker-Hub.

**Comment by larshp** [comment]
hmm, can try enabling the cron again, https://github.com/abaplint/abaplint-cloud-foundry/blob/master/.github/workflows/dockerimage.yml

**Comment by ed-holland** [comment]
nothing changed. It seems that the cron's never ran.

**Comment by larshp** [comment]
I'll try fixing it tomorrow

**Comment by larshp** [comment]
try again, https://hub.docker.com/r/abaplint/abaplint-backend/tags

I've not tested the build, but pull requests welcome for fixing, and now the docker image should publish at push to master

**Comment by ed-holland** [comment]
It is working fine now. Thanks.

Closing
