### ISSUE TITLE
(node:74) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

### ISSUE THREAD

**Issue by gregorwolf** [abaplint/abaplint-cloud-foundry#6]
In [check_object.ts#L36](https://github.com/abaplint/abaplint-cloud-foundry/blob/44ddd10c1e7c230f68d5150842efcc4559fa2c73/src/check_object.ts#L36) the function:

`new Buffer(f.contents, "base64")`

is used. According to [Porting to the Buffer.from()/Buffer.alloc()](https://nodejs.org/fr/docs/guides/buffer-constructor-deprecation/) this should be replaced by:

`Buffer.from(f.contents, "base64")`

I will give it a try.

**Comment by larshp** [comment]
yea, thanks 👍
